"""Generate synthetic store -> budgeted refresh -> print regret vs TTL/FIFO.

python scripts/run.py
"""

import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))

from regret.ablate import ablation
from regret.const import K, N_KEYS, N_TICKS, SEED, TRAIN_TICKS
from regret.engine import compare_policies, print_report

METRICS = "metrics.json"
DATA_TS = "web/src/metrics.gen.ts"


def write_metrics_ts(rows: dict, table: dict) -> None:
    if not os.path.exists(os.path.dirname(DATA_TS)):
        return
    r, ttl, fifo = rows["regret"], rows["ttl"], rows["fifo"]
    body = (
        "// Generated by scripts/run.py. Do not hand-edit.\n"
        f"export const ILLUSTRATIVE = false\n"
        f"export const METRICS = {{\n"
        f"  regretPct: {r['success_pct']},\n"
        f"  ttlPct: {ttl['success_pct']},\n"
        f"  fifoPct: {fifo['success_pct']},\n"
        f"  nKeys: {r['n_keys']},\n"
        f"  k: {r['k']},\n"
        f"  nTicks: {r['n_ticks']},\n"
        f"  trainTicks: {r['train_ticks']},\n"
        f"  nHeld: {r['n_held']},\n"
        f"  nQueries: {r['n_queries']},\n"
        f"  seed: {r['seed']},\n"
        f"}}\n"
        f"export const REGRET_TICKS: number[] = {json.dumps(r['per_tick'])}\n"
        f"export const TTL_TICKS: number[] = {json.dumps(ttl['per_tick'])}\n"
        f"export const FIFO_TICKS: number[] = {json.dumps(fifo['per_tick'])}\n"
        f"export const ABLATION_BUDGET = {json.dumps(table['budget'])}\n"
        f"export const ABLATION_PROXY = {json.dumps(table['proxy'])}\n"
    )
    with open(DATA_TS, "w", encoding="utf-8") as f:
        f.write(body)


def main() -> None:
    rows = compare_policies(
        n_keys=N_KEYS, k=K, n_ticks=N_TICKS, train_ticks=TRAIN_TICKS, seed=SEED
    )
    table = ablation(
        n_keys=N_KEYS, n_ticks=N_TICKS, train_ticks=TRAIN_TICKS, seed=SEED
    )
    blob = {name: m for name, m in rows.items()}
    blob["ablation"] = table
    with open(METRICS, "w", encoding="utf-8") as f:
        json.dump(blob, f, indent=2)
    print("ablation budget:")
    for r in table["budget"]:
        print(f"  k={r['k']:<3} regret {r['regret']:.2f}  ttl {r['ttl']:.2f}  fifo {r['fifo']:.2f}")
    print("ablation proxy:")
    for r in table["proxy"]:
        print(f"  {r['proxy']:<8} success_pct {r['success_pct']:.2f}")
    print_report(rows)
    write_metrics_ts(rows, table)


if __name__ == "__main__":
    main()
